### ISSUE TITLE
Missing values on map

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sw-flow-trends#112]
Glenn Hodgkins has spotted a few cases where gages are not appearing on the map for peak trend results. 
For example, for peak-flow results for 1916 in western NC, there should be three:

![image](https://user-images.githubusercontent.com/12058013/97120530-a9fa3100-16e5-11eb-9ab1-e4b8876e9cd1.png)

But only two show on the mapper (I have placed a circle approximately where the missing one should be). 

![image](https://user-images.githubusercontent.com/12058013/97120532-ad8db800-16e5-11eb-9c89-74b89799b752.png)

We have confirmed that there are trend results for all three of those gages for all three time periods in the [data release file 'trends.csv'](https://www.sciencebase.gov/catalog/item/5b183960e4b092d965219d62).
The three sites are:
NC03451500 (shown on the mapper, lat/long 35.608, -82.578)
NC03513000 (not shown on the mapper, lat/long 35.4275, -83.447)
NC03550000 (shown on the mapper, lat/long 35.139, -83.9805)
I wonder if it's a function of the mapping code or the source file being referenced. I have attached the 'trends.csv' file from the data release to this email for comparison.

[trends.zip](https://github.com/USGS-WiM/sw-flow-trends/files/5436045/trends.zip)

**Comment by njestes** [comment]
This turned out to be an issue with an old gage_characteristics.csv file that I referenced for all the site names and locations, but it turned out to be a little over a couple hundred sites short. Downloaded the newer complete one from ScienceBase and reprocessed all the data. Probably took care of several issues and at the very least the one described above.
